language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly
  - hhvm-nightly

matrix:
  allow_failures:
    - php: nightly
    - php: hhvm-nightly

before_script:
  - composer -n --prefer-source --dev install
  - php bin/console doctrine:database:create --env=test -n
  - php bin/console doctrine:schema:create --env=test -n
  - php bin/console doctrine:migrations:migrate --env=test -n

script: phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
