language: php

addons:
  hosts:
    - jeuxamateurs.fr
    - api.jeuxamateurs.fr

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script: composer -n --prefer-source --dev install

script: phpunit
