ja_app:
    type: rest
    resource: "@JAAppBundle/Resources/config/routing.yml"
    prefix:   /

ja_game:
    type: rest
    resource: "@JAGameBundle/Resources/config/routing.yml"
    prefix:   /

api_doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc