parameters:
    ja_game.game.handler.class: JA\GameBundle\Handler\GameHandler
    ja_game.game.class: JA\GameBundle\Entity\Game

services:
    ja_game.game.handler:
        class: %ja_game.game.handler.class%
        arguments: [@doctrine.orm.entity_manager, %ja_game.game.class%, @form.factory]
