ja_app_homepage:
    type: rest
    resource: "JA\AppBundle\Controller\HomepageController"
    name_prefix: api_1_

ja_app_game:
    type:     rest
    resource: "JA\AppBundle\Controller\GameController"
    name_prefix: api_1_

ja_app_user:
    type: rest
    resource: "JA\AppBundle\Controller\UserController"
    name_prefix: api_1_

ja_app_technology:
    type: rest
    resource: "JA\AppBundle\Controller\TechnologyController"
    name_prefix: api_1_
