parameters:
    ja_app.user.handler.class: JA\AppBundle\Handler\UserHandler
    ja_app.user.class: JA\AppBundle\Entity\User

services:
    ja_app.user.handler:
        class: %ja_app.user.handler.class%
        arguments: [@doctrine.orm.entity_manager, %ja_app.user.class%]
