parameters:
    ja_app.user.handler.class: JA\AppBundle\Handler\UserHandler
    ja_app.user.class: JA\AppBundle\Entity\User
    ja_app.game.class: JA\AppBundle\Entity\Game
    ja_app.game.handler.class: JA\AppBundle\Handler\GameHandler
    ja_app.technology.class: JA\AppBundle\Entity\Technology

services:
    ja_app.user.handler:
        class: %ja_app.user.handler.class%
        arguments: [@doctrine.orm.entity_manager, %ja_app.user.class%]
    ja_app.game.handler:
        class: %ja_app.game.handler.class%
        arguments: [@doctrine.orm.entity_manager, %ja_app.game.class%, @form.factory, @security.token_storage, @security.authorization_checker]
    ja_app.event_listener.avatar:
        class: JA\AppBundle\EventListener\AvatarListener
        arguments: [ "@gravatar.api" ]
        tags:
            -  { name: doctrine.event_listener, event: postLoad }
    ja_app.game_voter:
        class:      JA\AppBundle\Security\GameVoter
        arguments: [@security.role_hierarchy, @logger]
        public:     false
        tags:
           - { name: security.voter }