JA\AppBundle\Entity\Game:
    exclusion_policy: ALL
    properties:
        owner:
            expose: true
            groups: [details, list]
            recursion_groups:
                add: [list]
                remove: [details]