JA\AppBundle\Entity\Technology:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [details, list]
        name:
            expose: true
            groups: [details, list]
        slug:
            expose: true
            groups: [details, list]
        description:
            expose: true
            groups: [details, list]
        content:
            expose: true
            groups: [details]
        createdAt:
            expose: true
            groups: [details]
        updatedAt:
            expose: true
            groups: [details]
